- name: Check OS version and family
  fail:
      msg: "This role can only be run agaist RHEL 7. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when:
      - ansible_os_family == 'RedHat'
      - ansible_distribution_major_version | version_compare('7', '!=')
  tags:
      - always

- name: Check ansible version
  fail:
     msg: You must use ansible 2.1 or greater
  when: not ansible_version.full | version_compare('2.1', '>=')
  tags:
      - always

- name: "PRELIM | List users accounts"
  command: "awk -F: '{print $1}' /etc/passwd"
  register: users
  changed_when: false
  always_run: yes
  tags:
      - cat1
      - cat2

- name: Run preliminary Tasks
  include: prelim.yml
  tags:
      - prelim_tasks
      - always

- name: Include CAT I patches
  include: fix-cat1.yml
  when: rhel7stig_cat1_patch
  tags:
      - cat1
      - patch

- name: Include CAT II patches
  include: fix-cat2.yml
  when: rhel7stig_cat1_patch
  tags:
      - cat1
      - patch

- name: Include CAT III patches
  include: fix-cat3.yml
  when: rhel7stig_cat1_patch
  tags:
      - cat1
      - patch
